package ports

import "github.com/gofiber/fiber/v2"

// Handlers ...
type Handlers interface {
	// Login ...
	Login() fiber.Handler
	// Dashboard ...
	Dashboard() fiber.Handler
	// Me ...
	Me() fiber.Handler
	// ListProfiles ...
	ListProfiles() fiber.Handler
	// NewProfile ...
	NewProfile() fiber.Handler
	// ShowProfile ...
	ShowProfile() fiber.Handler
	// EditProfile ...
	EditProfile() fiber.Handler
	// CreateProfile ...
	CreateProfile() fiber.Handler
	// DeleteProfile ...
	DeleteProfile() fiber.Handler
	// ListEnvironments ...
	ListEnvironments() fiber.Handler
	// NewEnvironment ...
	NewEnvironment() fiber.Handler
	// ShowEnvironment ...
	ShowEnvironment() fiber.Handler
	// EditEnvironment ...
	EditEnvironment() fiber.Handler
	// UpdateEnvironment ...
	UpdateEnvironment() fiber.Handler
	// DeleteEnvironment ...
	DeleteEnvironment() fiber.Handler
	// CreateEnvironment ...
	CreateEnvironment() fiber.Handler
}
