package utils

const (
	CreateDesignCommentUrlFormat = "/designs/%s/comments"
	CreateDesignUrlFormat        = "/designs/new?template=%s"
	CreateEnvironmentUrlFormat   = "/environments"
	CreateLensUrlFormat          = "/lenses"
	CreateProfileUrlFormat       = "/profiles/new"
	CreateTagUrlFormat           = "/tags/new"
	CreateTemplateUrlFormat      = "/templates/new"
	CreateWorkloadUrlFormat      = "/workloads/new"
	DeleteDesignUrlFormat        = "/designs/%s"
	DeleteEnvironmentUrlFormat   = "/environments/%s"
	DeleteLensUrlFormat          = "/lenses/%s"
	DeleteProfileUrlFormat       = "/profiles/%s"
	DeleteTagUrlFormat           = "/tags/%s"
	DeleteTemplateUrlFormat      = "/templates/%s"
	EditBodyUrlFormat            = "/designs/%s/body/edit"
	EditTitleUrlFormat           = "/designs/%s/title/edit"
	ListTagsUrlFormat            = "/tags"
	ListTemplatesUrlFormat       = "/templates"
	ListWorkflowsUrlFormat       = "/workflows"
	ShowDesigUrlFormat           = "/designs/%s"
	ShowProfileUrlFormat         = "/profiles/%s"
	ShowTemplateUrlFormat        = "/templates/%s"
)
