package utils

const (
	CreateDesignCommentUrlFormat         = "/designs/%s/comments"
	CreateDesignUrlFormat                = "/designs/new?template=%s"
	CreateEnvironmentUrlFormat           = "/environments"
	CreateLensUrlFormat                  = "/lenses"
	CreateProfileUrlFormat               = "/profiles/new"
	CreateTagUrlFormat                   = "/tags/new"
	CreateWorkflowUrlFormat              = "/workflows/new"
	CreateTemplateUrlFormat              = "/templates/new"
	CreateWorkloadUrlFormat              = "/workloads/new"
	DeleteDesignUrlFormat                = "/designs/%s"
	DeleteEnvironmentUrlFormat           = "/environments/%s"
	DeleteLensUrlFormat                  = "/lenses/%s"
	DeleteProfileUrlFormat               = "/profiles/%s"
	DeleteTagUrlFormat                   = "/tags/%s"
	DeleteTemplateUrlFormat              = "/templates/%s"
	DeleteWorkflowsUrlFormat             = "/workflows/%s"
	EditBodyUrlFormat                    = "/designs/%s/body/edit"
	EditTitleUrlFormat                   = "/designs/%s/title/edit"
	EditWorkloadUrlFormat                = "/workloads/%s/edit"
	ListTagsUrlFormat                    = "/tags"
	ListTemplatesUrlFormat               = "/templates"
	ListWorkflowsUrlFormat               = "/workflows"
	ShowDesigUrlFormat                   = "/designs/%s"
	ShowProfileUrlFormat                 = "/profiles/%s"
	ShowTemplateUrlFormat                = "/templates/%s"
	ShowLensUrlFormat                    = "/lenses/%s"
	ShowWorkloadUrlFormat                = "/workloads/%s"
	ShowWorkflowUrlFormat                = "/workflows/%s"
	ShowEnvironmentUrlFormat             = "/environments/%s"
	DashboardStatsProfileUrlFormat       = "/stats/profiles"
	DashboardStatsDesignUrlFormat        = "/stats/designs"
	DashboardStatsWorkloadUrlFormat      = "/stats/workloads"
	WorkloadSearchLensesUrlFormat        = "/workloads/search/lenses"
	WorkloadSearchEnvironmentsUrlFormat  = "/workloads/search/environments"
	WorkloadSearchProfilesUrlFormat      = "/workloads/search/profiles"
	WorkloadLensUrlFormat                = "/workloads/%s/lenses/%s"
	DeleteWorkloadUrlFormat              = "/workloads/%s"
	DeleteDesignCommentReactionUrlFormat = "/designs/%s/comments/%s/reactions/%d"
	CreateDesignCommentReactionUrlFormat = "/designs/%s/comments/%s/reactions"
)
